--Item Table

DROP TABLE IF EXISTS &&1..ITEM_DETAILS CASCADE CONSTRAINTS;

CREATE TABLE &&1..ITEM_DETAILS 
(
	ITEM_ID INT AUTO_INCREMENT,
	ITEM_NAME VARCHAR(50) NOT NULL,
	ITEM_STATUS VARCHAR(20) NOT NULL,
	REMARKS VARCHAR(100),
	CREATED_DATE DATETIME NOT NULL,
	CREATED_BY VARCHAR(20) NOT NULL,
	UPDATED_DATE DATETIME,
	UPDATED_BY VARCHAR(20),
	CONSTRAINT itemid_pk PRIMARY KEY (ITEM_ID),
	CONSTRAINT item_name_uq UNIQUE (ITEM_NAME),
	CONSTRAINT createdby_fk FOREIGN KEY (CREATED_BY) REFERENCES &&1..USER (USER_ID),
	CONSTRAINT updatedby_fk FOREIGN KEY (UPDATED_BY) REFERENCES &&1..USER (USER_ID)
);