--Login Table

DROP TABLE IF EXISTS &&1..LOGIN_DETAIL CASCADE CONSTRAINTS;

CREATE TABLE &&1..LOGIN_DETAIL 
(	
	USER_ID VARCHAR(20),
	LAST_LOGIN DATETIME NOT NULL,
	CONSTRAINT userid_pk PRIMARY KEY (USER_ID),
	CONSTRAINT userid_ld_fk FOREIGN KEY (USER_ID) REFERENCES &&1..USER(USER_ID)
);