--Sales Transaction Table

DROP TABLE IF EXISTS &&1..SALES_TRANSACTION CASCADE CONSTRAINTS;

CREATE TABLE &&1..SALES_TRANSACTION 
(
	SALES_TRANSACTION_ID INT AUTO_INCREMENT,
	BILL_ID INT NOT NULL,
    BROKER_ID INT,
	ITEM_ID INT NOT NULL,
	RATE_PER_UNIT DECIMAL(10,2) NOT NULL,
	QUANTITY DECIMAL (8,2) NOT NULL,
	BASIC_AMOUNT DECIMAL(10,2) NOT NULL,
    BROKERAGE_PERCENTAGE DECIMAL(5,2) DEFAULT 0,
    BROKERAGE_AMOUNT DECIMAL(10,2) DEFAULT 0,
    BROKERAGE_AMOUNT DECIMAL(10,2) DEFAULT 0,
    TOTAL_AMOUNT DECIMAL(10,2) NOT NULL,
    CREATED_DATE DATETIME NOT NULL,
	CREATED_BY VARCHAR(20) NOT NULL,
	UPDATED_DATE DATETIME,
	UPDATED_BY VARCHAR(20),
    CONSTRAINT salesid_pk PRIMARY KEY (SALES_TRANSACTION_ID),
    CONSTRAINT billid_st_fk FOREIGN KEY (BILL_ID) REFERENCES &&1..BILL_DETAILS(BILLING_ID),
    CONSTRAINT brokerid_st_fk FOREIGN KEY (BROKER_ID) REFERENCES &&1..BROKER_DETAILS(BROKER_ID),
    CONSTRAINT itemid_st_fk FOREIGN KEY (ITEM_ID) REFERENCES &&1..ITEM_DETAILS(ITEM_ID),
    CONSTRAINT createdby_st_fk FOREIGN KEY (CREATED_BY) REFERENCES &&1..USER (USER_ID),
	CONSTRAINT updatedby_st_fk FOREIGN KEY (UPDATED_BY) REFERENCES &&1..USER (USER_ID)
);