--Security Question Table

DROP TABLE IF EXISTS &&1..SECURE_QUEST CASCADE CONSTRAINTS;

CREATE TABLE &&1..SECURE_QUEST
(
	SECURITY_QUESTION_ID INT AUTO_INCREMENT,
	SECURITY_QUESTION VARCHAR(100) NOT NULL,
	CREATED_DATE DATETIME NOT NULL,
	CREATED_BY VARCHAR(20) NOT NULL,
	CONSTRAINT sec_quesid_pk PRIMARY KEY (SECURITY_QUESTION_ID)   
);