--User Table

DROP TABLE IF EXISTS &&1..USER CASCADE CONSTRAINTS;

CREATE TABLE &&1..USER 
(
	USER_ID VARCHAR(20),
	PASSWORD VARCHAR(20) NOT NULL,
	USER_NAME VARCHAR(50) NOT NULL,
	STATUS VARCHAR(15) NOT NULL,
	USER_ROLE VARCHAR(10) NOT NULL,
	SECURITY_QUESTION_ID INT NOT NULL,
	SECURITY_ANSWER VARCHAR(50) NOT NULL,
	REMARKS VARCHAR(100),
	CONSTRAINT userid_pk PRIMARY KEY (USER_ID),
	CONSTRAINT user_role_ck CHECK(USER_ROLE IN ('User','Admin')),
	CONSTRAINT status_ck CHECK(STATUS IN ('Requested','Rejected','Active','Locked')),
	CONSTRAINT sec_quesid_fk FOREIGN KEY (SECURITY_QUESTION_ID) REFERENCES &&1..SECURE_QUEST (SECURITY_QUESTION_ID)
);